Add preferred layout name for new product page
Voog/design-zurich pull request #125
Opened 2021-03-19 09:36 UTC by robertpih

Related to #124

2021-05-19 13:31 UTC, siimha requested changes
[Siin](https://github.com/Voog/design-zurich/blob/master/components/menu-level-2.tpl#L21
) ka veel puudu, aga title jäta samaks.

2021-05-26 07:46 UTC, siimha approved these changes, later dismissed

2021-05-28 12:50 UTC, siimha approved these changes

2021-05-31 06:50 UTC, tanelj requested changes
Tehniliselt toimib kenasti, kuid paar kommentaari.

2021-05-31 06:50 UTC, tanelj commented on components/submenu-for-current.tpl
>    <section class="content-topbar">
II taseme menüü komponenti ei tohiks avalikus vaates välja joonistada, kui seal ühtegi elementi kuvada ei ole. Hetkel tekib joon.

![Screenshot 2021-05-31 at 09 45 35](https://user-images.githubusercontent.com/378755/120151491-f9ad5780-c1f4-11eb-951c-16a3bfb5aaca.png)

2021-05-31 06:50 UTC, tanelj commented on components/menu-breadcrumbs.tpl
> +{%- capture breadcrumbsScript -%}
`sd_breadcrumbs` ei ole mallis mõtet topelt renderdada. Seda tehakse juba `html-head` komponendis.
https://github.com/Voog/design-zurich/blob/4f6e153a0cbdbd30f91f43e6d838ced1b32e2f66/components/html-head.tpl#L63

Tuleks caprure teha kas head komponendis ning tema tulemit renderdada seal ja ja kasutada siin

2021-06-07 13:21 UTC, siimha approved these changes

2021-06-07 13:37 UTC, tanelj commented on components/submenu-for-current.tpl
> +{% if editmode or hasChildren  %}
Tegelikult ei ole `hasChildren` muutujat üldse vaja. Piisaks selle aseme

```liquid
{% if editmode or hasChildren  %}
```

nii:
```liquid
{% if hasChildren != blank  %}
```

2021-06-07 14:01 UTC, tanelj approved these changes

2021-06-07 14:02 UTC, merged